spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/auth
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

hiro:
  jwtSecret: This is Spring-React Security Example
  jwtAccessExpiration: 3600000
  jwtRefreshExpiration: 36000000

---

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "your client id"
            client-secret: "your client secret"
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email
          kakao:
            client-id: "your client id"
            client-secret: "your client secret"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정